# Site settings
title: zacblanco.github.io
email: zacblanco@live.com
description: > # this means to ignore newlines until "baseurl:"
 A simple tech blog to keepp you updated on my projects and for interesting 
 tips tricks and hacks.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://zacblanco.github.io" # the base hostname & protocol for your site
twitter_username: ZacBlanco
github_username:  ZacBlanco

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Permalinks
permalink:        none
relative_permalinks: true

# Setup
paginate:         1
author:
  name:           Zac Blanco
  url:            "http://zacblanco.github.io"
  email:          zacblanco@live.com

# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole




# Build settings
markdown: kramdown
