
# Setup
author:
  name:           Zac Blanco
  url:            "https://blanco.io"
  email:          zacdblanco@gmail.com

title: Zac Blanco
author: zac blanco
baseurl: ""
simple_search: http://google.com/search
description: zac's portfolio of professional and academic doings
name: zac
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

pages_list:
  Blog: 'blog/'
  Education: 'education/'
  Projects: 'projects/'
  About: 'about/'

# Permalinks
permalink:           none
relative_permalinks: false

