# Site settings
title: zacblanco.github.io
email: zacdblanco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A personal site to outline my professional experience, as well as showcase my small part-time projects.
 I enjoy writing posts from time to time whenever I learn something new or feel like sharing things with
 the world.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://zacblanco.github.io" # the base hostname & protocol for your site
twitter_username: ZacBlanco
github_username:  ZacBlanco

pages_list:       
  Projects: '/projects'
  Blog: '/blog'
  About: '/about'
  Feed: '/atom.xml'


# Permalinks
permalink:        none
relative_permalinks: true

# Setup
paginate:         1
author:
  name:           Zac Blanco
  url:            "http://zacblanco.github.io"
  email:          zacdblanco@gmail.com

# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole

# Build settings
markdown: kramdown
