# Site settings
title: Zac Blanco
email: zacdblanco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A personal site to outline my professional experience, as well as showcase my small part-time projects.
 I enjoy writing posts from time to time whenever I learn something new or feel like sharing things with
 the world.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blanco.io" # the base hostname & protocol for your site
twitter_username: ZacBlanco
github_username:  ZacBlanco

pages_list:    
  Blog: '/blog'
  Education: '/education'
  Projects: '/projects'
  About: '/about'
  

# Permalinks
permalink:           none
relative_permalinks: false  

# Setup
paginate:         1
author:
  name:           Zac Blanco
  url:            "http://blanco.io"
  email:          zacdblanco@gmail.com

# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole

# Build settings
markdown: kramdown
