# Site settings
title: Zac Blanco
email: zacdblanco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A personal website to act as a portfolio for my academic and professional experience
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://blanco.io" # the base hostname & protocol for your site
twitter_username: ZacBlanco
github_username:  ZacBlanco
tagline: hello

pages_list:    
  Blog: '/blog'
  Education: '/education'
  Projects: '/projects'
  About: '/about'
  

# Permalinks
permalink:           none
relative_permalinks: false  

# Setup
author:
  name:           Zac Blanco
  url:            "https://blanco.io"
  email:          zacdblanco@gmail.com

# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole

# Build settings
markdown: kramdown
